spring.application.name=Teo

# --- Configuración de Base de Datos (MySQL) ---
# URL: localhost, puerto 3306, base de datos 'teo_db' (se crea sola)
spring.datasource.url=jdbc:mysql://localhost:3306/teo_db?CreateDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuración de JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect